### ISSUE TITLE
Uploading image not working with either fs or db backend

### ISSUE THREAD

**Issue by DerKnerd** [penpot/penpot#1120]
**Describe the bug**
After running Penpot with the provided docker-compose file I cannot upload images. I get the following entry in the nginx log:

```
penpot-frontend_1  | 172.22.0.1 - - [28/Jul/2021:20:54:41 +0000] "POST /api/rpc/mutation/update-file HTTP/1.1" 200 148 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"
penpot-frontend_1  | 172.22.0.1 - - [28/Jul/2021:20:54:43 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 200 253 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"
penpot-frontend_1  | 2021/07/28 20:54:43 [error] 13#13: *1 open() "/opt/data/assets/3b/86/4fa4387e4750a2ab72fc1244c1b2" failed (2: No such file or directory), client: 172.22.0.1, server: _, request: "GET /assets/by-file-media-id/08ce33a0-efe6-11eb-8c38-25dca2baafc5 HTTP/1.1", upstream: "http://172.22.0.5:6060/assets/by-file-media-id/08ce33a0-efe6-11eb-8c38-25dca2baafc5", host: "localhost:9001", referrer: "http://localhost:9001/"
```

The config and docker-compose file are like the default config.

**Comment by DerKnerd** [comment]
I found the issue, the path mapping in the docker-compose.yaml is wrong. After changing it to the following it works:

```yaml
---
version: "3.5"

networks:
penpot:

volumes:
penpot_postgres_data:
penpot_assets_data:

services:
penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
    - 9001:80

    volumes:
    - penpot_assets_data:/opt/data/assets <- Here

    env_file:
    - config.env

    depends_on:
    - penpot-backend
    - penpot-exporter

    networks:
    - penpot

penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
    - penpot_assets_data:/opt/penpot/backend/assets <- Here

    depends_on:
    - penpot-postgres
    - penpot-redis

    env_file:
    - config.env

    networks:
    - penpot

penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
    # Don't touch it; this uses internal docker network to
    # communicate with the frontend.
    - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
    - penpot

penpot-postgres:
    image: "postgres:13"
    restart: always
    stop_signal: SIGINT

    environment:
    - POSTGRES_INITDB_ARGS=--data-checksums
    - POSTGRES_DB=penpot
    - POSTGRES_USER=penpot
    - POSTGRES_PASSWORD=penpot

    volumes:
    - penpot_postgres_data:/var/lib/postgresql/data

    networks:
    - penpot

penpot-redis:
    image: redis:6
    restart: always
    networks:
    - penpot
```
