### ISSUE TITLE
Set Canvas/Background Color of View Mode

### ISSUE THREAD

**Issue by nickian** [penpot/penpot#1125]
Would it be possible to add an option to change or override the color of the background in the view mode?

It's currently black and would be nice to change to a gray when working with a design that has a lot of black because it just kind of blends in with the canvas background.

Looks like it's coming from this CSS in `main-default.css`:

```css
.viewer-content {
  background-color: black;
  display: grid;
  grid-template-rows: 232px auto;
  grid-template-columns: 1fr;
}
```

Would it make sense to simply match this canvas color in both view/edit mode?:

![image](https://user-images.githubusercontent.com/590678/127750166-07e99a9f-a8f8-42d1-8819-55bd4dc63948.png)

Thanks! I'm loving the app so far.
