### ISSUE TITLE
Dynamic frontend uxbox config 

### ISSUE THREAD

**Issue by wizzytod** [penpot/penpot#296]
**Is your feature request related to a problem? Please describe.**
Config for frontend is figured out at build time from environment variables, saved in index.html script tag, and cannot be changed further. Running the same frontend application in different environments is not possible.

**Describe the solution you'd like**
I want to be able to modify uxbox frontend config (especially `publicURI` property) in runtime on the application start.

**Describe alternatives you've considered**
One of the possible solutions can be what is in https://github.com/taigaio/taiga-front done: 
1. keep config in the external JSON file (e.g. `/conf/conf.json`).
2. load config from it.
3. start the application after all properties initialized.

**Comment by niwinz** [comment]
Seems reasonable. How urgent this is for you?

**Comment by madmath03** [comment]
It's not "_urgent_" but this would definitely help make UXBOX more dynamic and work for any domain name without rebuilding frontend.

We plan to develop this ourselves, but we wanted to share this with you for information and in case you can give us any advice on how to implement it since it can have a big impact on starting UXBOX web app.

**Comment by niwinz** [comment]
I'll take a look at it tomorrow then ;)

**Comment by niwinz** [comment]
I think i have a solution for this. Right now the unique configuration needed on build time is the path to the worker (relative path). All the other can be deduced or defaulted. So i completely removed the static built time configuration.
For runtime config the default template will automatically load `/js/config.js` that by default contains empty values (almost empty file, the content is just a example of structure of the file). But you can overwrite it with custom values on the deployment phase.

**Comment by niwinz** [comment]
Now, our ansible deployment script looks like:

```yaml
    - name: Build Frontend APP
      shell:
        chdir: "{{repos_dir}}/uxbox/"
        cmd: ./manage.sh build-frontend
      delegate_to: localhost

    - name: Generate a config file
      delegate_to: localhost
      copy:
        content: |
          var appPublicURI = "https://{{ domain_name }}";
          var appGoogleClientID = {{ google_client_id | to_json }};
          var appDemoWarning = {{ is_demo | to_json }};
          var appDeployDate = {{ deploy_date | to_json }};
          var appDeployCommit = {{ deploy_commit_hash | to_json }};
        mode: preserve
        dest: "{{repos_dir}}/uxbox/frontend/target/dist/js/config.js"
```
