### ISSUE TITLE
bug: `disable-registration` does not prevent non-users from creating accounts in "share prototypes" page

### ISSUE THREAD

**Issue by abedef** [penpot/penpot#5164]
### Steps To Reproduce

1. disable registration via `disable-registration` flag
2. share a prototype and click "Get Link"
3. access the link from a new session to reveal a "Log in or sign up" option at the top of the screen
4. through this menu, I can register for an account and have verified that it is actually created via CLI lookup

### Expected behavior

I expect that, just as in the landing page, using the `disable-registration` flag should disable registration across the rest of the application.

### Actual behavior

The `disable-registration` flag disables registration on the landing page, but still allows registration on the share prototype page.

### Screenshots or video

<img width="475" alt="image" src="https://github.com/user-attachments/assets/c2f4554a-f7b7-4ae3-8296-2771bcd35ef2">
<img width="263" alt="image" src="https://github.com/user-attachments/assets/44f0bd5f-14fc-4ca0-bd22-1906d69687a0">
<img width="406" alt="image" src="https://github.com/user-attachments/assets/ca4461eb-5045-4633-b340-146f474adb38">
<img width="419" alt="image" src="https://github.com/user-attachments/assets/46fe0919-4cfb-476f-9a6e-dbe7ea90f0dc">

### Desktop (please complete the following information)

- OS: macOS 15.0.1 (24A348)
- Browser: Safari 18.0.1 (20619.1.26.31.7)

### Environment (please complete the following information)

- Host: local instance
- OS Version: Arch Linux
- Docker version: 27.1.1, build 63125853e3
- Image version: (default)

```yaml
# penpot.yml

networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9001:80

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

    labels:
      - "traefik.enable=true"

    environment:
      - PENPOT_FLAGS=disable-registration enable-login-with-password

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always

    volumes:
      - penpot_assets:/opt/data/assets

    depends_on:
      - penpot-postgres
      - penpot-redis

    networks:
      - penpot

    environment:
      - PENPOT_FLAGS=disable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server
      - PENPOT_PUBLIC_URI=http://localhost:9001
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_USERNAME=
      - PENPOT_SMTP_PASSWORD=
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot

    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
      - PENPOT_REDIS_URI=redis://penpot-redis/0

  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot
```

Deployed via the command `docker compose -p penpot -f penpot.yml up -d`
