### ISSUE TITLE
proxy_pass is hardcoded in nginx.conf

### ISSUE THREAD

**Issue by kgnfth** [penpot/penpot#596]
**Is your feature request related to a problem? Please describe.**
We are trying to create a one click app for https://github.com/caprover/caprover
but the problem is the nginx configuration for proxy_pass is hardcoded at https://github.com/penpot/penpot/blob/develop/docker/images/files/nginx.conf#L71-L86
thus we have to manually override the proxy_pass by patching it like this
```
- FROM penpotapp/frontend:1.1.0-alpha
- RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
- RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
```
it works but it'd be fragile for future releases of penpot.

this is my half working solution for caprover

```yaml
captainVersion: 4

services:
    $$cap_appname-db:
        image: 'postgres:13'
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_INITDB_ARGS: --data-checksums
            POSTGRES_DB: penpot
            POSTGRES_USER: penpot
            POSTGRES_PASSWORD: penpot
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-redis:
        image: 'redis:6'
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-exporter:
        image: 'penpotapp/exporter:1.1.0-alpha'
        restart: always
        environment:
            PENPOT_PUBLIC_URI: 'http://penpot-frontend'
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-backend:
        image: 'penpotapp/backend:1.1.0-alpha'
        volumes:
            - $$cap_appname-assets-data:/opt/data
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
            PENPOT_TELEMETRY_ENABLED: true
            PENPOT_SMTP_DEFAULT_FROM: $$cap_smtp_from
            PENPOT_SMTP_DEFAULT_REPLY_TO: $$cap_smtp_reply_to
            PENPOT_SMTP_HOST: $$cap_smtp_host
            PENPOT_SMTP_PORT: $$cap_smtp_port
            PENPOT_SMTP_USERNAME: $$cap_smtp_username
            PENPOT_SMTP_PASSWORD: $$cap_smtp_password
            PENPOT_SMTP_TLS: $$cap_smtp_tls
            PENPOT_SMTP_SSL: $$cap_smtp_ssl

            PENPOT_DATABASE_URI: postgresql://$$cap_appname-db/penpot
            PENPOT_DATABASE_USERNAME: penpot
            PENPOT_DATABASE_PASSWORD: penpot
            PENPOT_REDIS_URI: redis://$$cap_appname-redis/0
            PENPOT_STORAGE_BACKEND: fs
            PENPOT_STORAGE_FS_DIRECTORY: /opt/data/assets
            PENPOT_SMTP_ENABLED: true
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-redis
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-frontend:
        volumes:
            - $$cap_appname-assets-data:/opt/data
        caproverExtra:
            dockerfileLines:
                - FROM penpotapp/frontend:1.1.0-alpha
                - RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
                - RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
        depends_on:
            - $$cap_appname-backend
            - $$cap_appname-exporter

caproverOneClickApp:
    variables:
        - id: $$cap_public_uri
          label: Public URI
          defaultValue: https://penpot
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_from
          label: STMP from address
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_reply_to
          label: STMP reply address
          defaultValue: no-reply@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_host
          label: STMP host
          defaultValue: smtp.example.com
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_port
          label: STMP port
          defaultValue: 587
          validRegex: /^^((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))$$/
        - id: $$cap_smtp_username
          label: STMP username
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_password
          label: STMP password
          defaultValue:
          validRegex: /.{1,}/
        - id: $$cap_smtp_tls
          label: STMP TLS support
          defaultValue: true
          validRegex: /^(true|false)$/
        - id: $$cap_smtp_ssl
          label: STMP SSL support
          defaultValue: false
          validRegex: /^(true|false)$/
    instructions:
        start: >-
            The open-source solution for design and prototyping.
        end: >
            Penpot is deployed and available as $$cap_appname-frontend. IMPORTANT: It will take up to 2 minutes for Penpot to be ready. Before that, you might see a 502 error page.
    displayName: Penpot
    isOfficial: true
    description: The open-source solution for design and prototyping.
    documentation: Official docs are [here](https://github.com/penpot/penpot/tree/develop/docs)
```

But we are getting error for the backend ` Execution error (ExceptionInfo) at app.common.exceptions/error (exceptions.cljc:31).`

**Comment by niwinz** [comment]
Hi @kgnfth, it is not very clear that can happens because I don't know how caprover works, but from my understanding, it works like a template for create a complete docker-compose file. If this is correct, i see many issues with this config.
If I undertstand it correctly

```
- RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
- RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
```
should be:

```
- RUN sed -i 's/penpot-backend/$$cap_appname-backend/g' /etc/nginx/nginx.conf
- RUN sed -i 's/penpot-exporter/$$cap_appname-exporter/g' /etc/nginx/nginx.conf
```

Then 
```
    $$cap_appname-exporter:
        image: 'penpotapp/exporter:1.1.0-alpha'
        restart: always
        environment:
            PENPOT_PUBLIC_URI: 'http://penpot-frontend'
```
should be:

```
    $$cap_appname-exporter:
        image: 'penpotapp/exporter:1.1.0-alpha'
        restart: always
        environment:
            PENPOT_PUBLIC_URI='http://$$cap_appname-frontend'
```

And in fact, all env variables defined under `environment:` should follow `ENV_NAME=value` syntax instead of `ENV_NAME: value` and value always without quoting chars `"` or `'`. In the same way as they are defined here: https://github.com/penpot/penpot/blob/develop/docker/images/docker-compose.yaml

I hope this help solving the issue.

**Comment by kgnfth** [comment]
i have managed to make it fully working now

Demo: https://penpot.app.gocloud.fun/
click on `Create demo account`

Caprover talks to other containers using the prefix `srv-captain--`
```yaml
captainVersion: 4

services:
    $$cap_appname-db:
        image: 'postgres:13'
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_INITDB_ARGS: --data-checksums
            POSTGRES_DB: penpot
            POSTGRES_USER: penpot
            POSTGRES_PASSWORD: penpot
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-redis:
        image: 'redis:6'
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-exporter:
        image: 'penpotapp/exporter:1.1.0-alpha'
        restart: always
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-backend:
        image: 'penpotapp/backend:1.1.0-alpha'
        volumes:
            - $$cap_appname-assets-data:/opt/data
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
            PENPOT_TELEMETRY_ENABLED: 'false' # no one wants this enabled anyway
            PENPOT_SMTP_DEFAULT_FROM: $$cap_smtp_from
            PENPOT_SMTP_DEFAULT_REPLY_TO: $$cap_smtp_reply_to
            PENPOT_SMTP_HOST: $$cap_smtp_host
            PENPOT_SMTP_PORT: $$cap_smtp_port
            PENPOT_SMTP_USERNAME: $$cap_smtp_username
            PENPOT_SMTP_PASSWORD: $$cap_smtp_password
            PENPOT_SMTP_TLS: $$cap_smtp_tls
            PENPOT_SMTP_SSL: $$cap_smtp_ssl

            PENPOT_DATABASE_URI: postgresql://srv-captain--$$cap_appname-db/penpot
            PENPOT_DATABASE_USERNAME: penpot
            PENPOT_DATABASE_PASSWORD: penpot
            PENPOT_REDIS_URI: redis://srv-captain--$$cap_appname-redis:6379/0
            PENPOT_STORAGE_BACKEND: fs
            PENPOT_STORAGE_FS_DIRECTORY: /opt/data/assets
            PENPOT_SMTP_ENABLED: 'true'
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-redis
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname:
        volumes:
            - $$cap_appname-assets-data:/opt/data
        caproverExtra:
            dockerfileLines:
                - FROM penpotapp/frontend:1.1.0-alpha
                - RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
                - RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
        depends_on:
            - $$cap_appname-backend
            - $$cap_appname-exporter

caproverOneClickApp:
    variables:
        - id: $$cap_public_uri
          label: Public URI
          defaultValue: https://penpot
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_from
          label: STMP from address
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_reply_to
          label: STMP reply address
          defaultValue: no-reply@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_host
          label: STMP host
          defaultValue: smtp.example.com
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_port
          label: STMP port
          defaultValue: 587
          validRegex: /^^((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))$$/
        - id: $$cap_smtp_username
          label: STMP username
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_password
          label: STMP password
          defaultValue:
          validRegex: /.{1,}/
        - id: $$cap_smtp_tls
          label: STMP TLS support
          defaultValue: true
          validRegex: /^(true|false)$/
        - id: $$cap_smtp_ssl
          label: STMP SSL support
          defaultValue: false
          validRegex: /^(true|false)$/
    instructions:
        start: >-
            The open-source solution for design and prototyping.
        end: >
            Penpot is deployed and available as $$cap_appname. IMPORTANT: It will take up to 2 minutes for Penpot to be ready. Before that, you might see a 502 error page.
    displayName: Penpot
    isOfficial: true
    description: The open-source solution for design and prototyping.
    documentation: Official docs are [here](https://github.com/penpot/penpot/tree/develop/docs)

```
the variables under `caproverOneClickApp `are configurable in the one click setup

**Comment by kgnfth** [comment]
@niwinz 

I have managed to make it fully working now.

The environment variables are correct it looks like a docker-compose file but caprovers template is different


Demo: https://penpot.app.gocloud.fun/
click on `Create demo account`

Caprover talks to other containers using the prefix `srv-captain--`
```yaml
captainVersion: 4

services:
    $$cap_appname-postgres:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_INITDB_ARGS: --data-checksums
            POSTGRES_DB: penpot
            POSTGRES_USER: penpot
            POSTGRES_PASSWORD: $$cap_postgres_pass
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-redis:
        image: redis:$$cap_redis_version
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-exporter:
        image: penpotapp/exporter:$$cap_penpot_exporter_version
        restart: always
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-backend:
        image: penpotapp/backend:$$cap_penpot_backend_version
        volumes:
            - $$cap_appname-assets-data:/opt/data
        environment:
            PENPOT_PUBLIC_URI: $$cap_public_uri
            PENPOT_TELEMETRY_ENABLED: $$cap_enable_telemetry
            PENPOT_SMTP_DEFAULT_FROM: $$cap_smtp_from
            PENPOT_SMTP_DEFAULT_REPLY_TO: $$cap_smtp_reply_to
            PENPOT_SMTP_HOST: $$cap_smtp_host
            PENPOT_SMTP_PORT: $$cap_smtp_port
            PENPOT_SMTP_USERNAME: $$cap_smtp_username
            PENPOT_SMTP_PASSWORD: $$cap_smtp_password
            PENPOT_SMTP_TLS: $$cap_smtp_tls
            PENPOT_SMTP_SSL: $$cap_smtp_ssl

            PENPOT_DATABASE_URI: postgresql://srv-captain--$$cap_appname-postgres/penpot
            PENPOT_DATABASE_USERNAME: penpot
            PENPOT_DATABASE_PASSWORD: $$cap_postgres_pass
            PENPOT_REDIS_URI: redis://srv-captain--$$cap_appname-redis:6379/0
            PENPOT_STORAGE_BACKEND: fs
            PENPOT_STORAGE_FS_DIRECTORY: /opt/data/assets
            PENPOT_SMTP_ENABLED: 'true'
        depends_on:
            - $$cap_appname-postgres
            - $$cap_appname-redis
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname:
        volumes:
            - $$cap_appname-assets-data:/opt/data
        caproverExtra:
            dockerfileLines:
                - FROM penpotapp/frontend:$$cap_penpot_frontend_version
                - RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
                - RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
        depends_on:
            - $$cap_appname-backend
            - $$cap_appname-exporter

caproverOneClickApp:
    variables:
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: '13'
          description: Checkout their docker description page for the valid tags https://hub.docker.com/r/lycheeorg/lychee/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_redis_version
          label: Redis Version
          defaultValue: '6'
          description: Checkout their docker desctiption page for the valid tags https://hub.docker.com/_/redis?tab=description
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_penpot_frontend_version
          label: Penpot Frontend Version
          defaultValue: '1.1.0-alpha'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/penpotapp/frontend/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_penpot_backend_version
          label: Penpot Backend Version
          defaultValue: '1.1.0-alpha'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/penpotapp/backend/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_penpot_exporter_version
          label: Penpot Exporter Version
          defaultValue: '1.1.0-alpha'
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/penpotapp/exporter/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_pass
          label: Potgress Database password
          description: 'Pasword for postgres'
          validRegex: /.{1,}/
        - id: $$cap_public_uri
          label: Public URI
          defaultValue: https://penpot
          description: 'Frontend url to access your Penpot'
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_from
          label: STMP from address
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_reply_to
          label: STMP reply address
          defaultValue: no-reply@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_host
          label: STMP host
          defaultValue: smtp.example.com
          validRegex: /^^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/
        - id: $$cap_smtp_port
          label: STMP port
          defaultValue: 587
          validRegex: /^^((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))$$/
        - id: $$cap_smtp_username
          label: STMP username
          defaultValue: user@example.com
          validRegex: /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
        - id: $$cap_smtp_password
          label: STMP password
          defaultValue:
          validRegex: /.{1,}/
        - id: $$cap_smtp_tls
          label: STMP TLS support
          defaultValue: true
          validRegex: /^(true|false)$/
        - id: $$cap_smtp_ssl
          label: STMP SSL support
          defaultValue: false
          validRegex: /^(true|false)$/
        - id: $$cap_enable_telemetry
          label: Send Anonymous Data
          description: When enabled, a periodical process will send annonymous data about this instance. Read more at https://github.com/yverdon/taiga6/blob/957112f6cdcd9fb5ea50c4c42a9695aa9018dcd2/docker-compose.penpot.yml#L58-L64
          defaultValue: false
          validRegex: /^(true|false)$/
          
    instructions:
        start: >-
            The open-source solution for design and prototyping.
        end: >
            Penpot is deployed and available as http://$$cap_appname.$$cap_root_domain. IMPORTANT: It will take up to 2 minutes for Penpot to be ready. Before that, you might see a 502 error page.
    displayName: Penpot
    isOfficial: true # it is Penpot's official image
    description: The open-source solution for design and prototyping.
    documentation: Official docs are [here](https://github.com/penpot/penpot/tree/develop/docs)

```
the variables under `caproverOneClickApp `are configurable in the one click setup
