### ISSUE TITLE
Error starting exporter

### ISSUE THREAD

**Issue by sardaukar** [penpot/penpot#746]
**Describe the bug**
Exporter container crashes on startup

**To Reproduce**
1.  Run penpot with the following docker-compose.yml:
```
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_data:
  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 11478:80

    volumes:
      - penpot_assets_data:/opt/data

    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - penpot_assets_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    environment:
      - PENPOT_REGISTRATION_ENABLED=false
      - PENPOT_REGISTRATION_DOMAIN_WHITELIST="tld.net"
      - PENPOT_PUBLIC_URI=https://domain.tld
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_STORAGE_BACKEND=fs
      - PENPOT_STORAGE_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false
      - PENPOT_SMTP_ENABLED=true
      - PENPOT_SMTP_DEFAULT_FROM=email@domain.tld
      - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@domain.tld
      - PENPOT_SMTP_HOST=smtp host
      - PENPOT_SMTP_PORT=587
      - PENPOT_SMTP_USERNAME=smtp username
      - PENPOT_SMTP_PASSWORD=smtp password
      - PENPOT_SMTP_TLS=true
      - PENPOT_SMTP_SSL=false

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - penpot_postgres_data:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:6
    restart: always
    networks:
      - penpot
```
2. exporter container never starts

**Expected behavior**
Exporter container doesn't crash on startup

**Screenshots**
```
libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at Cluster.<anonymous> (/opt/app/node_modules/puppeteer-cluster/dist/Cluster.js:119:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/app/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[app.core] {:msg "initializing", :line 26}
(node:1) UnhandledPromiseRejectionWarning: Error: Unable to launch browser, error message: Failed to launch the browser process!
/opt/app/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory
```

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser firefox
-   Version 86

**Environment (please complete the following information):**
Self-hosted instance.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Debian 10

Also provide Docker commands or docker-compose file if possible and if proceed.x

See above

**Frontend Stack Trace (if self-hosted)**

N/A

**Backend Stack Trace (if self-hosted)**

see above

**Additional context**
